"""Tests for bitFlyer ExchangeApiClient authentication and signature generation

This test verifies that signature generation works correctly after the refactoring
that distinguishes between relative_stub_path and stub_path.

Key verification items:
1. endpoint_path in signature message generated by _build_auth_headers starts with '/'
2. endpoint_path generated by each Private API method is correct
3. Correct distinction between relative_stub_path (no slash) and stub_path (with slash)
"""

import httpx
import pytest
from pydantic import SecretStr
from yarl import URL

from crypto_api_client.bitflyer.bitflyer_api_client_factory import (
    BitFlyerApiClientFactory,
)
from crypto_api_client.http._http_method import HttpMethod


class TestExchangeApiClientEndpointPathGeneration:
    """Test endpoint_path generation in ExchangeApiClient

    Detects the issue where removing '/' from stub_path during refactoring
    caused endpoint_path to not start with '/', resulting in signature errors.
    """

    @pytest.fixture
    def factory(self):
        """Factory instance"""
        return BitFlyerApiClientFactory()

    @pytest.fixture
    def api_client(self, factory):
        """API client for testing"""
        http_client = httpx.AsyncClient()
        client = factory.create(
            api_key=SecretStr("test_api_key"),
            api_secret=SecretStr("test_api_secret"),
            http_client=http_client,
            callbacks=None,
            request_config={"timeout": 30.0},
        )
        return client

    def test_relative_stub_path_does_not_start_with_slash(self, factory):
        """Verify relative_stub_path doesn't start with '/'

        Specification after refactoring: relative_stub_path doesn't start with '/'
        """
        config = factory.get_default_config()
        relative_stub_path = config["relative_stub_path"]

        # relative_stub_path doesn't start with '/'
        assert not relative_stub_path.path.startswith("/")
        # relative_stub_path is 'v1'
        assert relative_stub_path.path == "v1"

    def test_endpoint_path_generation_for_private_api(self, factory, api_client):
        """Verify endpoint_path generation for Private API is correct

        Important: endpoint_path must always start with '/' (for signature generation)
        """
        config = factory.get_default_config()

        # Test case: getbalance
        resource_path = config["relative_resource_identifier_path"].joinpath(
            config["getbalance_action_name"].path
        )

        # endpoint_path generation logic actually used in ExchangeApiClient
        # Uses ApiClient.stub_path property (slash added automatically)
        endpoint_path = api_client.stub_path / resource_path.path

        # endpoint_path starts with '/'
        assert endpoint_path.path.startswith("/"), (
            f"endpoint_path must start with '/'. Got: {endpoint_path.path}"
        )

        # Expected: /v1/me/getbalance
        assert endpoint_path.path == "/v1/me/getbalance"

    def test_all_private_api_endpoint_paths_start_with_slash(self, factory):
        """Verify all Private API endpoint_paths start with '/'"""
        config = factory.get_default_config()

        # All Private API endpoints
        private_api_actions = [
            ("getbalance", "getbalance_action_name"),
            ("getchildorders", "getchildorders_action_name"),
            ("sendchildorder", "sendchildorder_action_name"),
            ("cancelchildorder", "cancelchildorder_action_name"),
            ("getexecutions", "getexecutions_action_name"),
            ("gettradingcommission", "gettradingcommission_action_name"),
        ]

        for api_name, action_key in private_api_actions:
            resource_path = config["relative_resource_identifier_path"].joinpath(
                config[action_key].path
            )

            # endpoint_path generation logic actually used in ExchangeApiClient
            endpoint_path = URL("/") / config["relative_stub_path"].path / resource_path.path

            # endpoint_path must always start with '/'
            assert endpoint_path.path.startswith("/"), (
                f"{api_name}: endpoint_path must start with '/'. Got: {endpoint_path.path}"
            )

            # endpoint_path starts with '/v1/me/'
            assert endpoint_path.path.startswith("/v1/me/"), (
                f"{api_name}: endpoint_path should start with '/v1/me/'. Got: {endpoint_path.path}"
            )

    def test_build_auth_headers_signature_format(self, api_client):
        """Verify _build_auth_headers generates signature in correct format

        This is an integration test that calls the actual signature generation logic.
        """
        # Test parameters
        endpoint_path = URL("/v1/me/getbalance")
        timestamp = "1640000000000"

        # Call _build_auth_headers
        headers = api_client._build_auth_headers(
            api_key=SecretStr("test_api_key"),
            api_secret=SecretStr("test_api_secret"),
            method=HttpMethod.GET,
            endpoint_path=endpoint_path,
            query_params=None,
            request_body=None,
            timestamp=timestamp,
        )

        # Verify headers are correctly generated
        assert "ACCESS-KEY" in headers
        assert "ACCESS-TIMESTAMP" in headers
        assert "ACCESS-SIGN" in headers

        # Verify timestamp is correct
        assert headers["ACCESS-TIMESTAMP"] == timestamp

    def test_regression_endpoint_path_without_leading_slash_would_fail(self, factory):
        """Regression test: detect issue when endpoint_path doesn't start with '/'

        This test is meant to detect future occurrences of the problem that happened
        when '/' was removed from stub_path during refactoring.

        If incorrectly implemented as follows, this test will fail:
            endpoint_path = stub_path.joinpath(resource_path.path)
            # → 'v1/me/getbalance' (no leading '/')
        """
        config = factory.get_default_config()

        resource_path = config["relative_resource_identifier_path"].joinpath(
            config["getbalance_action_name"].path
        )

        # [Incorrect implementation] Using stub_path directly (doesn't start with '/')
        wrong_endpoint_path = config["relative_stub_path"].joinpath(resource_path.path)

        # [Correct implementation] Explicitly adding '/'
        correct_endpoint_path = URL("/") / config["relative_stub_path"].path / resource_path.path

        # Incorrect implementation doesn't start with '/'
        assert not wrong_endpoint_path.path.startswith("/"), (
            "This demonstrates the bug: endpoint_path doesn't start with '/'"
        )

        # Correct implementation starts with '/'
        assert correct_endpoint_path.path.startswith("/"), (
            "Correct implementation: endpoint_path must start with '/'"
        )

        # Both are different
        assert wrong_endpoint_path.path != correct_endpoint_path.path


class TestExchangeApiClientPrivateApiIntegration:
    """Integration tests for Private API methods

    Verify that actual Private API methods generate correct endpoint_path.
    However, actual HTTP requests are not sent (using mocks/stubs).
    """

    @pytest.fixture
    async def api_client(self):
        """API client for testing"""
        factory = BitFlyerApiClientFactory()
        async with httpx.AsyncClient() as http_client:
            client = factory.create(
                api_key=SecretStr("test_api_key"),
                api_secret=SecretStr("test_api_secret"),
                http_client=http_client,
                callbacks=None,
                request_config={"timeout": 30.0},
            )
            yield client

    def test_private_api_methods_use_correct_endpoint_path_format(self):
        """Verify all Private API methods use correct endpoint_path format

        This test statically checks each method's implementation.
        Actual HTTP requests are not sent.
        """
        factory = BitFlyerApiClientFactory()
        config = factory.get_default_config()

        # stub_path is 'v1' (doesn't start with '/')
        assert config["relative_stub_path"].path == "v1"

        # However, endpoint_path generated by each Private API method
        # must always start with '/'

        # This expects the implementation to be like:
        # endpoint_path = URL("/") / self._api_config["relative_stub_path"].path / resource_path.path

        # This requirement has been verified in the TestEndpointPathGeneration class above


class TestPrivateApiMethodsEndpointPath:
    """Verify Private API methods generate correct endpoint_path

    This confirms endpoint_path is correct during actual method calls.
    """

    @pytest.fixture
    async def api_client(self):
        """API client for testing"""
        factory = BitFlyerApiClientFactory()
        async with httpx.AsyncClient() as http_client:
            client = factory.create(
                api_key=SecretStr("test_api_key"),
                api_secret=SecretStr("test_api_secret"),
                http_client=http_client,
                callbacks=None,
                request_config={"timeout": 30.0},
            )
            yield client

    async def test_getbalance_generates_correct_endpoint_path(self, api_client, mocker):
        """Verify getbalance() uses correct endpoint_path"""
        from crypto_api_client.bitflyer._signature_builder import build_message

        # Mock build_message to capture passed endpoint_path
        original_build_message = build_message
        captured_endpoint_paths = []

        def mock_build_message(**kwargs):
            captured_endpoint_paths.append(kwargs["endpoint_path"])
            return original_build_message(**kwargs)

        mocker.patch(
            "crypto_api_client.bitflyer.exchange_api_client.build_message",
            side_effect=mock_build_message
        )

        # Mock HTTP request to avoid actual communication
        mock_response = mocker.Mock()
        mock_response.status_code = 200
        mock_response.text = '[]'
        mock_response.headers = {}
        mocker.patch.object(
            api_client._http_client,
            "request",
            return_value=mock_response
        )

        # Call getbalance()
        try:
            await api_client.getbalance()
        except Exception:
            pass  # Ignore errors (purpose is to capture endpoint_path)

        # Verify endpoint_path is correct
        assert len(captured_endpoint_paths) > 0
        endpoint_path = captured_endpoint_paths[0]

        # endpoint_path must always start with '/'
        assert endpoint_path.path.startswith("/"), (
            f"endpoint_path must start with '/'. Got: {endpoint_path.path}"
        )

        # endpoint_path is '/v1/me/getbalance'
        assert endpoint_path.path == "/v1/me/getbalance", (
            f"Expected '/v1/me/getbalance', got: {endpoint_path.path}"
        )


class TestSignatureGenerationRegression:
    """Regression tests for signature generation

    Tests to detect issues that occurred in the past.
    """

    def test_signature_changes_when_endpoint_path_format_changes(self):
        """Verify signature changes when endpoint_path format changes

        This demonstrates that the presence/absence of '/' affects the signature.
        """
        from crypto_api_client.bitflyer._signature_builder import build_message

        timestamp = "1640000000000"

        # Starts with '/' (correct)
        msg_correct = build_message(
            method=HttpMethod.GET,
            endpoint_path=URL("/v1/me/getbalance"),
            query_params=None,
            request_body=None,
            timestamp=timestamp,
        )

        # Doesn't start with '/' (incorrect)
        msg_wrong = build_message(
            method=HttpMethod.GET,
            endpoint_path=URL("v1/me/getbalance"),
            query_params=None,
            request_body=None,
            timestamp=timestamp,
        )

        # Signature messages differ
        assert msg_correct != msg_wrong

        # Correct format: "1640000000000GET/v1/me/getbalance"
        assert msg_correct == "1640000000000GET/v1/me/getbalance"

        # Incorrect format: "1640000000000GETv1/me/getbalance"
        assert msg_wrong == "1640000000000GETv1/me/getbalance"
